# Generated by Django 6.0.6 on 2026-08-17 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category_alter_product_sku_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_active', '-created_at'], name='review_product_active_created'),
        ),
    ]
