# Generated by Django 6.0.6 on 2026-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='stores/banners/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
