# Generated by Django 6.0.6 on 2026-08-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_options_alter_store_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
